### ISSUE TITLE
File placement

### ISSUE THREAD

**Issue by zLapis06** [amrrs/py_img_convertor#3]
The files can be in any Path?

**Comment by amrrs** [comment]
Hey Sorry @zLapis06 How did you find this? Is this solved/

**Comment by zLapis06** [comment]
I use tkinter filedialog.askopenfilename

**Comment by amrrs** [comment]
@zLapis06 For the file path, it takes from the current working directory

**Comment by zLapis06** [comment]
Buy if i use tkinter filedialog i can enter amy path with a variable

**Comment by amrrs** [comment]
Ideally it should work, did you try?

**Comment by zLapis06** [comment]
Yes

**Comment by zLapis06** [comment]
It works

**Comment by amrrs** [comment]
Awesome!
